"""
BP 修订脚本包
提供目标定位、证据处理、修订流程、API 搜索、会话记忆等功能
"""

from .helpers import (
    match_target_keywords,
    search_product_aliases,
    calculate_evidence_confidence,
    generate_writeback_patch,
    run_consistency_check,
    generate_validation_report,
    calculate_time_distance,
    in_responsibility_chain,
    merge_patches,
    create_three_segment_output,
    search_tasks_by_name,
    get_task_tree,
    get_goal_detail,
    search_groups_by_name,
    remember_corrected_rule,
    get_session_memory,
    clear_session_memory,
    apply_session_memory,
    check_core_principles,
    save_checkpoint,
    get_checkpoint,
    resume_checkpoint,
    pause_task,
    resume_task,
    split_batch_input,
    detect_major_defects,
)

from .bp_reviser import (
    TargetStandard,
    EvidenceBundle,
    RevisionOutput,
    locate_target,
    inject_standard,
    downgrade_user_feedback,
    search_responsibility_chain,
    classify_evidence,
    determine_light_color,
    gate_decision,
    apply_writeback_patch,
    run_flow_consistency_check,
    main_reviser_flow,
    LayerEnum,
    BPTypeEnum,
    EvidenceLevelEnum,
    RevisionStatusEnum,
    RevisionActionEnum,
)

__all__ = [
    # helpers - core data
    "match_target_keywords",
    "search_product_aliases",
    "calculate_evidence_confidence",
    "generate_writeback_patch",
    "run_consistency_check",
    "generate_validation_report",
    "calculate_time_distance",
    "in_responsibility_chain",
    "merge_patches",
    "create_three_segment_output",
    # helpers - API integration
    "search_tasks_by_name",
    "get_task_tree",
    "get_goal_detail",
    "search_groups_by_name",
    # helpers - session memory
    "remember_corrected_rule",
    "get_session_memory",
    "clear_session_memory",
    "apply_session_memory",
    "check_core_principles",
    # helpers - checkpoint
    "save_checkpoint",
    "get_checkpoint",
    "resume_checkpoint",
    "pause_task",
    "resume_task",
    "split_batch_input",
    # bp_reviser - core classes
    "TargetStandard",
    "EvidenceBundle",
    "RevisionOutput",
    # bp_reviser - flow functions
    "locate_target",
    "inject_standard",
    "downgrade_user_feedback",
    "search_responsibility_chain",
    "classify_evidence",
    "determine_light_color",
    "gate_decision",
    "apply_writeback_patch",
    "run_flow_consistency_check",
    "main_reviser_flow",
    # bp_reviser - enums
    "LayerEnum",
    "BPTypeEnum",
    "EvidenceLevelEnum",
    "RevisionStatusEnum",
    "RevisionActionEnum",
]
